config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'dresses', to: 'dresses#index'
  # get 'dresses/new', to: 'dresses#new'
  # get 'dresses', to: 'dresses#create'
  # get 'dresses/:dress_id', to: 'dresses#show', as: :dress
  resources :dresses do
    resources :bookings, only: [ :new, :create ]
  end
  resources :bookings, only: [ :index, :edit, :update, :show, :destroy ] do
      member do
        post :approve
        post :decline
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dress
  validates :created_date, presence: true
  validates :end_date, presence: true
end

app/models/dress.rb
class Dress < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  # validates :photos, presence: true
  CURRENCIES = ["GBP", "EUR", "AED", "USD"]
  EVENT_TYPES = ["Bridal", "Wedding", "Cocktail Party"]
  validates :currency, inclusion: { in: CURRENCIES }
  validates :event_type, inclusion: { in: EVENT_TYPES }

  include PgSearch::Model
  pg_search_scope :search,
                  against: %i[event_type size price description name],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :dresses
  has_many :incoming_bookings, through: :dresses, source: :bookings
  has_many :borrowed_dresses, through: :bookings, class_name:"Dress", source: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @dress = Dress.find(params[:dress_id])
    @booking.dress = @dress
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render "dresses/show"
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @dress = @booking.dress
    @user = @booking.user
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)

    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete
    redirect_to bookings_path
  end

  def approve
    @user = current_user
    @booking = Booking.find(params[:id])
    @booking.update(status: "approved")
    redirect_to user_path(@user)
  end

  def decline
    @user = current_user
    @booking = Booking.find(params[:id])
    @booking.update(status: "declined")
    redirect_to user_path(@user)
  end

  def booking_params
    params.require(:booking).permit(:created_date, :end_date)
  end
end

app/controllers/dresses_controller.rb
class DressesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show]
  before_action :set_dress, only: [ :show, :edit, :destroy ]
  def index
    if params[:query]
      @dresses = Dress.search(params[:query])
    else
      @dresses = Dress.all
    end
    return unless params[:event_type]

    @dresses = Dress.where(event_type: params[:event_type])
  end

  def new
    @dress = Dress.new
  end

  def create
    @dress = Dress.new(dress_params)
    @dress.user = current_user
    if @dress.save
      redirect_to dress_path(@dress)
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
  end

  def edit
  end

  def update
    @dress = Dress.find(params[:id])
    @dress.update(dress_params)
    redirect_to dress_path(@dress)
  end

  def destroy
    @dress.destroy
    redirect_to user_path(@dress.user)
  end

  private

  def set_dress
    @dress = Dress.find(params[:id])
  end

  def dress_params
    params.require(:dress).permit(:name, :description, :price, :size, :retail_price, :currency, :event_type, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    if params[:query]
      @dresses = Dress.search(params[:query])
    else
      @dresses = Dress.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#show page
  def show
    @user = current_user
    @dresses = @user.dresses
    @borrowed_dresses = @user.bookings
    @my_bookings = Booking.where(dress: @user.dresses)
    @pending_bookings = @user.incoming_bookings.where(status: "pending")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.input :created_date %>
  <%= f.input :end_date %>
  <%= f.button :submit %>
<% end %>

app/views/bookings/edit.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.input :created_date,  as: :date, html5: true  %>
  <%= f.input :end_date, as: :date, html5: true  %>
  <%= f.submit class: "btn btn-sm btn-outline-secondary" %>
<% end %>

app/views/bookings/index.html.erb
<h2 style="text-align: center">Your bookings</h2>

<div class="card-booking">
  <div class="card-booking-infos">
    <% @bookings.each do |booking| %>
      <p><%= booking.created_date.strftime("%A, %B %e, %Y") %></p>
      <p><%= booking.end_date.strftime("%A, %B %e, %Y") %></p>
      <p><%= booking.dress.name %></p>
      <p><%= booking.dress.description %></p>
      <%= link_to "Edit Booking", edit_booking_path(booking) %>
      <%= link_to "Cancel Booking", booking, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>

app/views/bookings/new.html.erb
<%= simple_form_for [@dress, @booking] do |f| %>
  <%= f.input :created_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true  %>
  <%= f.button :submit %>
<% end %>

app/views/bookings/show.html.erb
<div class="booking-container">
  <div class="d-flex justify-content-between align-items-end">
    <h2>Thank You For Your Order!</h2>
    <%= link_to "Manage your bookings", user_path(@user), class: "button-primary" %>
  </div>
  <div class="booking-info">
    <div class="d-flex justify-content-around">
      <% if @dress.photos.any? %>
        <%= cl_image_tag @dress.photos.first.key, height: 300, width: 200, crop: :fill, class: "show-photo" %>
      <% end %>
    </div>
    <div class="booking">
      <h3><%= @dress.name.upcase %></h3>
      <br>
      <p><strong>BOOKING CONFIRMATION #:</strong> <%= @booking.id %></p>
      <p><strong>ORDER TOTAL:</strong> <%= @dress.price %> <%= @dress.currency %></p>
      <p><strong>FROM:</strong> <%= @booking.created_date.strftime("%A, %B %e, %Y") %></p>
      <p><strong>TO:</strong> <%= @booking.created_date.strftime("%A, %B %e, %Y") %></p>
    </div>
  </div>
</div>

app/views/dresses/edit.html.erb
<%= simple_form_for(@dress) do |f| %>
  <%= f.input :name, class: "form-control" %>
  <%= f.input :description, class: "form-control" %>
  <%= f.input :price, class: "form-control" %>
  <%= f.input :currency, collection: Dress::CURRENCIES, class: "form-control" %>
  <%= f.input :size, class: "form-control" %>
  <%= f.input :retail_price %>
  <%= f.input :currency, collection: Dress::CURRENCIES, class: "form-control" %>
  <%= f.input :event_type, collection: Dress::EVENT_TYPES, class: "form-control" %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.button :submit, class:"button-primary" %>
<% end %>

app/views/dresses/index.html.erb
<p id="notice"><%= notice %></p>
<!-- <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(https://wwd.com/wp-content/uploads/2018/09/bkstg-elie-saab-rtw-spring-2019-paris-fashion-week-pfw-044.jpg); margin-top: -15px; margin-bottom: 50px;">

  <div class="banner-header">
    <h2>Dresses for every occasion</h2>
  </div>
</div> -->

<%= form_tag dresses_path, method: :get do %>
  <div class="search">
    <%= text_field_tag :query,
        params[:query],
        class: "search-form-control",
        placeholder: "Find a dress..."
        %>
    <button name="button" type="submit" class="submit-button">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>

<div class="cards cards-grid">
    <% @dresses.each do |dress| %>
      <%= link_to dress_path(dress) do  %>
        <div class="dress-card">
          <% if dress.photos.any? %>
            <%= cl_image_tag dress.photos.first.key, height: 280, width: 280, crop: :fill %>
          <% end %>
          <div class="dress-card-info">
            <h3><%= dress.name.upcase %></h3>
            <p><%= dress.description %></p>
            <p><%= dress.price %> <%= dress.currency %> </p>
            <p><%= dress.size %></p>
            <p>Retail: <%= dress.retail_price %> <%= dress.currency %> </p>
            <p><% dress.event_type %></p>
          </div>
        </div>
      <% end %>
    <% end %>
</div>

app/views/dresses/new.html.erb
<div class="new-form-container">
  <h1> Add a New Dress</h1>
  <div class = "new-dress-form">
    <%= simple_form_for(@dress) do |f| %>
      <%= f.input :name, class: "form-control" %>
      <%= f.input :description, class: "form-control" %>
      <%= f.input :price, class: "form-control" %>
      <%= f.input :currency, collection: Dress::CURRENCIES, class: "form-control" %>
      <%= f.input :size, class: "form-control" %>
      <%= f.input :retail_price %>
      <%= f.input :currency, collection: Dress::CURRENCIES, class: "form-control" %>
      <%= f.input :event_type, collection: Dress::EVENT_TYPES, class: "form-control" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.button :submit, class:"button-primary" %>
    <% end %>
  </div>
</div>

app/views/dresses/show.html.erb
<div class="container">
  <div class="row pt-3">
    <div class="col-md-6 height-card d-flex justify-content-center">
      <%if @dress.photos.any? %>
        <%= cl_image_tag @dress.photos.first.key, class: "default-dress" %>
      <%else %>
        <%= image_tag "default_dress.jpg", class: "default-dress" %>
      <% end %>
    </div>
    <div class="col-md-6 align-text height-card" >
      <div class="card-grid">
        <div class ="dress-info">
          <div class ="title">
            <h1><%= @dress.name.upcase %></h1>
          </div>
          <div class="event">
            <h2>Event - <%= @dress.event_type %></h2>
          </div>
          <div class ="paragraph">
            <p><%= @dress.description %></p>
            <p>Size : <%= @dress.size %></p>
          </div>
          <div class ="dressprice">
            <p>Price: <%= @dress.price%> <%= @dress.currency%> &nbsp;&nbsp;&nbsp;(Retail: <%= @dress.retail_price%> <%= @dress.currency%>)</p>
          </div>
          <div id= dress-booking-form class="col mt-5 p-0 text-center" >
            <% if @dress.user == current_user %>
              <div class = "links">
                <%= link_to "Edit Dress", edit_dress_path(@dress), class: "btn btn-flat" %>
                <%= link_to "Remove Dress", dress_path(@dress), method: :delete, data: {confirm: "Are you sure you want to delete this dress?"}, class: "btn btn-flat" %>
              </div>
            <%else %>
              <div class ="form">
                <%= simple_form_for([@dress, @booking]) do |f| %>
                  <%= f.input :created_date, as: :date, html5: true, label: "FROM" %>
                  <%= f.input :end_date, as: :date, html5: true, label: "TO" %>
                  <%= f.button :submit, class: "button-primary" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dressbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container">
      <%= render "shared/navbar" %>
      <% unless action_name == 'home' %>
        <div style="height: 80px;"></div>
      <% end %>
    <!-- <p class="notice"> <#%= notice %></p>
    <p class="alert"><#%= alert %></p> -->
    <div class="content-container">
      <%= yield %>
    </div>
     <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div id="home" class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(https://wwd.com/wp-content/uploads/2018/09/bkstg-elie-saab-rtw-spring-2019-paris-fashion-week-pfw-044.jpg); margin-top: -15px; margin-bottom: 50px;">
  <div class="banner-header">
    <div class="row m-0">
      <div class="callout col-sm-5" id="titles">
        <div class= "title-text">
          <h1 id= "homepage-title"><strong>DressBnB</strong></h1>
          <p class="description">Got plans? The perfect space to Dress and Impress!</p>
        </div>
      </div>
    </div>
    <div class="row m-0">
      <div class="col-sm-4 pl-5">
        <div class="btn btn-flat mr-3 home-buttons">
          <%= link_to 'Rent a Dress', dresses_path %>
        </div>
        <div class="btn btn-flat home-buttons ml-2" id="button-transparency">
          <%= link_to 'Become a Lender', new_dress_path %>
        </div>
      </div>
    </div>
    <%= form_tag dresses_path, method: :get do %>
      <div class="home-search">
        <%= text_field_tag :query,
        params[:query],
        class: "home-search-form-control",
        placeholder: "Find a dress..."
        %>
      <button name="button" type="submit" class="submit-button">
        <i class="fas fa-search"></i> Search
      </button>
      </div>
    <% end %>
  </div>
</div>

<div class= "container-fluid">
  <div class= "category-cards d-flex justify-content-center mt-8 mb-8">
    <%= link_to dresses_path(event_type: 'Bridal') do %>
      <div class= "home-cards">
        <img src="https://travelbar.com/wp-content/uploads/2017/12/unsctw.jpg" alt="" class= "home-image" style="object-fit: cover;">
        <h2>Bridal Celebration</h2>
        <p>Express and define your special day.</p>
      </div>
    <% end %>

    <%= link_to dresses_path(event_type: 'Wedding') do %>
      <div class= "home-cards">
        <img src="https://cdn.designer-24.com/catalog/product/samr1589286197058_resized_480x.jpg" alt="" class= "home-image" style="object-fit: cover;">
        <h2>Wedding Celebration</h2>
        <p>Unique looks, with a divine feeling.</p>
      </div>
    <% end %>

    <%= link_to dresses_path(event_type: 'Cocktail Party') do %>
      <div class= "home-cards">
        <img src="https://cdn.designer-24.com/catalog/product/soab1589290517825_resized_480x.jpg" alt="" class= "home-image" style="object-fit: cover;">
        <h2>Cocktail Party</h2>
        <p>A style for every story.</p>
      </div>
    <% end %>
  </div>
  <%= link_to dresses_path do %>
    <div class= "button-primary-homepage">
      <h4 class= "d-flex justify-content-center">All Dresses</h4>
    </div>
  <% end %>
</div>

app/views/shared/_avatar.hmtl.erb
<%= image_tag "https://kitt.lewagon.com/placeholder/users/cveneziani", class: "avatar", alt: "avatar" %>
<%= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", class: "avatar-large", alt: "avatar-large" %>
<%= image_tag "https://kitt.lewagon.com/placeholder/users/sarahlafer", class: "avatar-bordered", alt: "avatar-bordered" %>
<%= image_tag "https://kitt.lewagon.com/placeholder/users/krokrob", class: "avatar-square", alt: "avatar-square" %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-sticky <%= 'navbar-white' unless action_name == 'home' %>">
    <%= link_to "Dress BnB", root_path, class: "nav-link" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active d-flex justify-content-end">
          <a class="nav-link" href="/dresses">View all Dresses</a>
          <a class="nav-link" href="/dresses/new">Add a Dress</a>
        </li>

        <li class="nav-item dropdown">
        <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", user_path(current_user), class: "dropdown-item"%>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>

<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "Dress BnB", dresses_path %>
  </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/dresses/new">Add a Dress</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_in">Sign In</a>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="profile">
  <h1 id="welcome" class="justify-content-center" > Welcome <%= current_user.email %> ! </h1>

  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation" >
      <a class="nav-link active" data-toggle="tab" id="dresses-tab" href="#dresses" role="tab" area-controls="dresses" area-selected="true" >Dresses</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" data-toggle="tab" id="bookings-tab" href="#bookings" role="tab" area-controls="bookings" area-selected="false">Bookings</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" data-toggle="tab" role="tab" id="request-tab" href="#requests" area-controls="requests" area-selected="false">Requests</a>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="pt-3">
      <div class="tab-pane fade show active" id="dresses" area-labelledby="dresses-tab" role="tabpanel">
        <div class="cards cards-grid">
          <% @dresses.each do |dress| %>
            <div class="dress-card">
              <%if dress.photos.any? %>
                <%= cl_image_tag dress.photos.first.key, height: 280, width: 250, crop: :fill %>
              <% end %>
              <div class="dress-card-info">
                <div class ="card-title">
                  <h3><%= dress.name %></h3>
                  <div>
                    <%= link_to edit_dress_path(dress) do %>
                      <i class="fas fa-edit"></i>
                    <% end %>
                    <%= link_to "X", dress_path(dress), method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                </div>
                <p><%= dress.description %></p>
                <p><%= dress.price %></p>
                <p><%= dress.size %></p>
                <div class="card-bottom">
                  <p><% dress.event_type %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="tab-pane fade" id="bookings" area-labelledby="bookings-tab" role="tabpanel">
        <div class="cards cards-grid" >
          <% @borrowed_dresses.each do |booking| %>
            <div class="dress-card">
              <% if booking.dress.photos.any? %>
                <%= cl_image_tag booking.dress.photos.first.key, height: 280, width: 250, crop: :fill %>
              <% end %>
              <div class="dress-card-info">
                <h3><%= link_to booking.dress.name.upcase, dress_path(booking.dress) %></h3>
                <p><%= booking.dress.description %></p>
                <p><%= booking.dress.price %><%= booking.dress.currency %></p>
                <p><%= booking.dress.currency %></p>
                <p><%= booking.dress.size %></p>
                <p>RETAIL: <%= booking.dress.retail_price %></p>
                <p><% booking.dress.event_type %></p>
                <% if booking.status == "pending"%>
                  <p>pending</p>
                <% elsif booking.status == "approved"%>
                  <p id="approved">approved</p>
                <% else %>
                  <p id="declined">declined</p>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="tab-pane fade" id="requests" area-labelledby="request-tab" role="tabpanel">
        <div class="cards cards-grid" >
          <% @pending_bookings.each do |booking| %>
            <div class="dress-card">
              <% if booking.dress.photos.any? %>
                <%= cl_image_tag booking.dress.photos.first.key, height: 280, width: 250, crop: :fill %>
              <% end %>
              <div class="dress-card-info">
                <h3><%= link_to booking.dress.name.upcase, dress_path(booking.dress) %></h3>
                <p><%= booking.dress.description %></p>
                <p><%= booking.dress.price %><%= booking.dress.currency %></p>
                <p><%= booking.dress.currency %></p>
                <p><%= booking.dress.size %></p>
                <p>RETAIL: <%= booking.dress.retail_price %></p>
                <p><% booking.dress.event_type %></p>
                <% if booking.status == "pending"%>
                  <div class="d-flex justify-content-between pt-2">
                    <%= link_to 'Approve', approve_booking_path(booking), class: "button-xs success", method: :post %>
                    <%= link_to 'Decline', decline_booking_path(booking), class: "button-xs success", method: :post %>
                  </div>
                <% elsif booking.status == "approved"%>
                  <p id="approved">approved</p>
                <% else %>
                  <p id="declined">declined</p>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>